#!/bin/bash

echo ""
echo "✓ rv-cli scaffold complete"
echo ""
echo "Project structure:"
find app -type f -name "*.py" | sort
echo ""
echo "To start using the app:"
echo ""
echo "1. Install Poetry: curl -sSL https://install.python-poetry.org | python3 -"
echo "2. Install dependencies: poetry install"
echo "3. Install PostgreSQL (if needed): brew install postgresql@16"
echo "4. Add PostgreSQL to your PATH (either run):"
echo "   - For Intel Macs: export PATH=\"/usr/local/opt/postgresql@16/bin:\$PATH\""
echo "   - For Apple Silicon: export PATH=\"/opt/homebrew/opt/postgresql@16/bin:\$PATH\""
echo "   - Or just run: source scripts/setup_env.sh"
echo "5. Set up your .env file with OpenAI API key"
echo "6. Initialize the database: make db-init"
echo ""
echo "Run the API:  make dev"
echo "Run the CLI:  ./rv.sh new"
echo ""
echo "Happy remote viewing!"
echo "" 